In [ ]:
# Slicing arrays
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [1]:
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17])

print(arr[1:5])

[12 13 14 15]


In [2]:
# Slice elements from index 4 to the end of the array:
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17])

print(arr[4:])

[15 16 17]


In [3]:
# Slice elements from the beginning to index 4 (not included):
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17])

print(arr[:4])

[11 12 13 14]


In [7]:
# Negative Slicing
# Use the minus operator to refer to an index from the end:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:-3])

[1 2 3 4]


In [4]:
# Negative Slicing
# Use the minus operator to refer to an index from the end:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:0])

[]


In [5]:
# STEP
# Use the step value to determine the step of the slicing:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [4]:
# STEP
# Use the step value to determine the step of the slicing:
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17,18, 19,20])

print(arr[1:9:2])

[12 14 16 18]


In [7]:
# Return every other element from the entire array:
import numpy as np

arr = np.array([11, 12, 13, 14, 15, 16, 17])

print(arr[::2])

[11 13 15 17]


In [13]:
#Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


In [24]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[1,2,3,4,5]])

print(arr[-3:-1, 2])

[3 8]


In [25]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
