In [2]:
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.

In [ ]:
#Why Use NumPy?
#In Python we have lists that serve the purpose of arrays, but they are slow to process.

#NumPy aims to provide an array object that is up to 50 times faster than traditional Python lists.

#The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

#Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
#Why is NumPy Faster Than Lists?
#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

#This behavior is called locality of reference in computer science.

#This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [ ]:
#Which Language is NumPy written in?
#NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [9]:
a = "100"
print(type(a))

<class 'str'>


In [10]:
import numpy as np

# array()
# array([1, 2, 3, 4, 5])

demo = np.array([1, 2, 3, 4, 5])
print(demo)
# arr = np.array([1, 2, 3, 4, 5])
# print(arr)
print(type(demo))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.zeros(4)

print(arr)
print(type(arr))


[0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [8]:
#Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [3]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

test = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(test)
print(test.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [13]:
#Check how many dimensions the arrays have:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
# print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]


In [6]:
#Array indexing is the same as accessing an array element.
#The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
import numpy as np

arr = np.array([11, 12, 13, 14])

print(arr[2])

13


In [17]:
#Get the second element from the following array.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [19]:
#Get third and fourth elements from the following array and add them.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [10]:
#Access 2-D Arrays
#Access the element on the first row, second column:
import numpy as np

arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

print('2nd element on 1st row: ', arr[1,1])

2nd element on 1st row:  5


In [22]:
#Access the element on the 2nd row, 5th column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [2]:
#Access 3-D Arrays
import numpy as np

arr = np.array([0, [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.