In [ ]:
# Random Numbers in NumPy
# What is a Random Number?
# Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [ ]:
# Pseudo Random and True Random.
# Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

# If there is a program to generate random number it can be predicted, thus it is not truly random.

# Random numbers generated through a generation algorithm are called t.

# Can we make truly random numbers?

# Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

# We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

# In this tutorial we will be using pseudo random numbers.

In [ ]:
# Generate Random Number
# NumPy offers the random module to work with random numbers.

In [22]:
# Example:Generate a random integer from 0 to 100:
from numpy import random

# arr = np.array([1,2,3,4,5])

x = random.randint(100)

print(x)

62


In [ ]:
# Generate Random Float
# The random module's rand() method returns a random float between 0 and 1.

In [69]:
# Example:Generate a random float from 0 to 1:
from numpy import random

x = random.rand()

print(x)

0.6643385896349059


In [ ]:
# Generate Random Array
# In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

# Integers
# The randint() method takes a size parameter where you can specify the shape of an array.

In [52]:
# Example:Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(10, size=(5))

print(x)

[0 3 7 1 0]


In [68]:
# Example:Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(20, size=(3, 5))

print(x)

[[18  7 19 14 18]
 [19  4 19 17 19]
 [ 4  7  3 19  7]]


In [6]:
# Floats:The rand() method also allows you to specify the shape of the array.
# Example:Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)

[0.53098378 0.7298847  0.54340092 0.63413112 0.53943569]


In [7]:
# Example:Generate a 2-D array with 3 rows, each row containing 5 random numbers:

from numpy import random

x = random.rand(3, 5)

print(x)

[[0.26218799 0.47621603 0.94419699 0.01140749 0.2045561 ]
 [0.67903797 0.60490339 0.72336989 0.43027592 0.06446954]
 [0.87448787 0.57419087 0.61062909 0.44490908 0.5791138 ]]
