In [ ]:
# NumPy Filter Array
# Filtering Arrays
# Getting some elements out of an existing array and creating a new array out of them is called filtering.
# In NumPy, we filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to indexes in the array.
# If the value at an index is True that element is contained in the filtered array, if the value at that index is False 
# that element is excluded from the filtered array.

In [4]:
# Example:Create an array from the elements on index 0 and 2:
import numpy as np

test = np.array([41, 42, 43, 44])

print(test)

x = [True, False, True, False]

newarr = test[x]

print(newarr)

[41 42 43 44]
[41 43]


In [2]:
# Example:Create an array from the elements on index 0 and 2:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [False, False, False, False]

newarr = arr[x]

print(newarr)

[]


In [ ]:
# The example above will return [41, 43]
# Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

In [ ]:
# Creating the Filter Array
# In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [8]:
# Example:Create a filter array that will return only values higher than 42:
import numpy as np

test = np.array([41, 42, 43, 44])

print(test) #[41 42 43 44]
# Create an empty list
demo_list = []

# go through each element in arr
for element in test:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    demo_list.append(True)
  else:
    demo_list.append(False)

print(demo_list)

newarr = test[demo_list]

print(newarr)

[41 42 43 44]
[False, False, True, True]
[43 44]


In [13]:
# Example:Create a filter array that will return only even elements from the original array:
import numpy as np

test = np.array([1, 2, 3, 4, 5, 6, 7])

print(test)

# Create an empty list
test_demo = []

# go through each element in arr
for element in test:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 1:
    test_demo.append(True)
  else:
    test_demo.append(False)

print(test_demo)

newarr = test[test_demo]

# print(filter_arr)
print(newarr)

[1 2 3 4 5 6 7]
[True, False, True, False, True, False, True]
[1 3 5 7]


In [ ]:
# Creating Filter Directly From Array
# The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.
# We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [14]:
# Example:Create a filter array that will return only values higher than 42:
import numpy as np

test = np.array([41, 42, 43, 44])

filter_arr = test > 42

newarr = test[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [5]:
# Example:Create a filter array that will return only even elements from the original array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
